### ISSUE TITLE
Demo links are broken

### ISSUE THREAD

**Issue by goatandsheep** [dperini/nwxforms#12]
Both Dropbox links seem to be broken and aren't working.

**Comment by dperini** [comment]
Thank you for reporting the problem.
I have fixed this. It was a problem with Dropbox.
They changed their policy about rendering HTML files.
No problem, I am know hosting that myself so it will survive longer. :)
Enjoy my humble contribution, hope it fits your needs and meets your requirements.
Have a nice day !

**Comment by goatandsheep** [comment]
Yeah it's pretty frustrating that they've done that. I've moved to [surge.sh](http://surge.sh/) for my static hosting. Thanks for fixing that! :sparkling_heart:
