### ISSUE TITLE
Don't check value but check if checkbox is checked

### ISSUE THREAD

**Issue by espen** [dperini/nwxforms#9]
Allows non-checked checkbox with required attribute.

**Comment by dperini** [comment]
Could you be a bit more specific or point to the block/line of code that generate the problem ?
Does it have to do with "grouping" controls ? Or does it happens for single check-box too ?
A simple test for the expected behavior would help me hunting/fixing.
Thank you for the suggestion.

**Comment by espen** [comment]
http://jsbin.com/nubokukoki/3/

Tested in Safari which does not support 'required' when submitting form.

**Comment by dperini** [comment]
Thank you !
I will work on a fix this weekend.

**Comment by dperini** [comment]
@espen,
the problem seems resolved to me.
Please test and report success/failure.
Thank you for your help and suggestion.
